import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <nav className="site-nav">
          <Link href="/products">商品一覧</Link>
          <Link href="/cart">カート</Link>
          <Link href="/orders">注文履歴</Link>
          <Link href="/mypage">マイページ</Link>
          <Link href="/login">ログイン</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
