spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ec_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Tokyo
    open-in-view: false       # OSIV は明示的に false 推奨

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  messages: # 追加
    basename: messages # 追加
    encoding: UTF-8 # 追加

server:
  port: 8080

logging:
  level:
    com.example: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE  # バインドパラメータをログ出力
