spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

batch:
  input:
    flag-file-template: ./tmp/batch/input/payment_confirmed_%s.done
  output:
    dir: ./tmp/batch/output
